travis:
  secure:
    BINSTAR_TOKEN: FMSAI/Wr8CXhidnpRV09w404US0BjHSk2OEYXAURu/Oa4PE6o/jbDv2udZVyEPtmwbvFGONiaBvJ1WFTInk3LpqTO4i5pjRqjHi1Pz92qv9w+25ao1GuBX/J1+yqu8lUyxPyLVGn7UZ4Vd+/BK57i8/bN5Rspr+2EgoomtAZKodg96yUwUfxhMghVi5CgRu4yERujmtPPOYW3tZgoHpp/uTN1Qyi9OSsFua7fQ6bOPQ/9Yhe1T/CmRdckRYo2rQzn9xHbtBwAEhHX46aC0huVReZ7bxeDQBEl8RiWgox+UwfBZ9LkEEhgS4VVwRkJI9JedW1JOO+DpJIn/tCjX0ALN5lg1welqwkMMZg+3DnRgsP6NCTASqZXSxdFTa+1ghmCxbg0dZvg5Doj/LPCFpaYO9+09Gq2LIox7bAZyQ/mgVLvAip2EY+2eCcy1zLqaV2qOPfAJ8SGgclHq+i6U4Nari6apTDDnylo/rfMOG00+KV9zTWFoQtlXcvTdwAcKCYZ47JAXQaQzv9y1l700sQm8XbDiFIm44/gh3cbuCxPgXL1efzjjRElJMGPw5Pyq0saVRnqnH/nJZavndDJlNbF3ncyWzYqxVk3yzEQk4+n+7FyRtl1Ra3X76IoyeLcy3FxS710H6mKKYEFkNgE/W+3dwy8MH/2el6X40o9wn1DHs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
