travis:
  secure:
    BINSTAR_TOKEN: EaE+1islXTHIrS/VpScogUHuGCHjH+bqSuWc/3S8GtfI7HeM2hFpBl4bJNm/+7X8AtNBypRu+6lSsNT+UTMGFZGf4u4bjzesTHZvb3/5Mqt4k0FVWW1Txe0qEwAGmZ0u2sKPybaM9JOsU3PnK31vRi/XoPUJHKFw7hxWe3dP0pUEqSyXjK+iPS5JAALD2XyqIZ4aEXRK7tQ1tStxV98k+Lw7dgyp5Dlr8m3R5FLw4f9rZRjdL0KznoGoucEGDwLau84lCXpnvKLWd7rH9B0WJxUNeBA3eQToI/YmgaTUGws0L5YXdTTDX5NmsEtAoZrKuFke1vPs1BLl2YCsiqiTAYrGZCRuHcoKu/VCz7OO9VMVZz+eKaC8UDx7t5MUPP3r7ieWbEDOC2ukeAMZ8X9KrJVb9oUIWWc8lERY1PCTgHUXYo7bJWEP57qpv6D54jFO1FIUn1JXWvGq6jUWFAr5sdr8eUwi9RCTW5ExHswh8Twp9bcPV4wxZC9GOzmDHPGxbfBjNPljvzIP16g/BC7XwUehcnAp8kal8AKoqTwUFGRj8m18euAE2jQvVHAyc4d/3jaaFglCdwJEgW+ZiojDjYISyJpfPCZ+YUR4UWMJnw4qH5NLbLAEqS10isbetV3mhp5wd/c7VtLp1LLeH9QYlEOuwMT3/fM2GvAdgA1qpiY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
